---
---
# Scifate Demo: Single-Cell RNA Dynamics with `sciflow`

This notebook demonstrates how to load, structure, inspect and analyze a Scifate-style single-cell RNA dataset using the `sciflow` package.

--- 

## Table of Contents

<div style="font-size: 1.15em; line-height: 1.6;">

1. <a href="#1-introduction"><b>Introduction</b></a>  
2. <a href="#2-what-is-scifate"><b>What is Scifate?</b></a>  
3. <a href="#3-loading-the-data"><b>Loading the Data</b></a>  
4. <a href="#4-inspecting-the-dataset-object"><b>Inspecting the Dataset</b></a>  

</div>

---
---

In [1]:
# std lib imports

# 3-party import
import pandas as pd

# projekt imports
from sciflow.data.scifate_dataset import ScifateDataLoader, ScifateDataset

---
---

## 1. Introduction

The goal of this notebook is to demonstrate how `sciflow` handles biological high-dimensional data.

---
---

## 2. What is Scifate?

---
---

## 3. Loading the Data

In the following section, the different data structures used for handling and organizing the dataset are introduced.

--- 

### Data Structures

The package is built around three core data structures:

#### `Dataset`

The `Dataset` class represents the general high-level container for structured datasets.

It stores:

- the underlying data matrix
- sample metadata (`sample_info`)
- feature metadata (`feature_info`)
- dataset-level information such as the dataset name

The class provides a unified interface for accessing dataset dimensions and general dataset properties.


#### `LabeledSparseMatrix`

The `LabeledSparseMatrix` is the central structure used for handling high-dimensional sparse data efficiently.

It combines:

- a sparse matrix representation
- row metadata
- column metadata
- label-aware indexing and filtering

The object supports:

- view-based subsetting without duplicating the underlying matrix
- efficient sparse storage
- metadata-based filtering
- row/column selection
- labeled matrix export as pandas DataFrames

This structure is especially useful for single-cell datasets where matrices are extremely sparse and strongly coupled with metadata.


#### `ScifateDataset`

The `ScifateDataset` extends the generic `Dataset` class and represents a dataset specifically tailored to the SciFate format.

It combines:

- the expression matrix
- optional NTR/RNA dynamics information
- cell metadata
- gene metadata
- trajectory information

The dataset internally uses `LabeledSparseMatrix` objects to store both expression and NTR matrices together with 
their corresponding annotations. This provides a convenient interface for working with biological high-dimensional 
data while keeping sparse operations memory efficient.

---

### Using the `ScifateDataLoader`

To work with a `ScifateDataset`, we use the `ScifateDataLoader` that is responsible for:

- locating the required dataset files  
- reading them from disk  
- ensuring consistent dimensions  
- transforming all matrices into a unified format  
- constructing a structured `ScifateDataset` object

In [2]:
scifate_loader = ScifateDataLoader()

**Option 1 — Load from folder**

In [3]:
scifate_data = scifate_loader.load(folder_path="/home/nicolas/code/master/higdim/HighDim/data/ScifateData")

**Option 2 — Load from individual files**

In [4]:
scifate_data_ = scifate_loader.load(
    expression_matrix_path="/home/nicolas/code/master/higdim/HighDim//data/ScifateData/matrix.mtx",
    ntr_matrix_path="/home/nicolas/code/master/higdim/HighDim//data/ScifateData/4sU.Binom.ntr.mtx",
    barcodes_path="/home/nicolas/code/master/higdim/HighDim//data/ScifateData/barcodes.tsv",
    features_path="/home/nicolas/code/master/higdim/HighDim//data/ScifateData/features.tsv",
    trajectories_path="/home/nicolas/code/master/higdim/HighDim//data/ScifateData/trajectories_sci.csv",
)

Avter we loaded the dataset we can look at the summary to see that everything worked fine.

In [5]:
print(scifate_data.summary())

ScifateDataset(
  name = SciFateDataset,
  shape = 7404 cells × 43750 genes,
  ntr = yes,
  cell_info = yes,
  gene_info = yes
)

---
---

## 4. Working with the Dataset

After loading the dataset, the expression matrix, NTR matrix, and metadata can be accessed directly. The expression_matrix and the ntr_matrix are `LabeledSparseMatrix` objects.
The Gene Info and the Cell Info will be `pandas.Dataframes` that contain multible features that represent infos about the rows and columns of the NTR matrix and expression Matrix.

---

### Inspecting the data within the dataset

In [6]:
# let's look at the gene info (info about the columns of the ntr and expression matrix)
scifate_data.gene_info.head()

           gene_id gene_name     feature_type            region  length
0  ENSG00000225602  MTOR-AS1  Gene Expression  Exonic (h.ens90)     705
1  ENSG00000171819   ANGPTL7  Gene Expression  Exonic (h.ens90)    2238
2  ENSG00000238173   RPL39P6  Gene Expression  Exonic (h.ens90)     150
3  ENSG00000239149  SNORA59A  Gene Expression  Exonic (h.ens90)     152
4  ENSG00000204518   AADACL4  Gene Expression  Exonic (h.ens90)    1575

In [7]:
# let's look at the cell info (info about the rows of the ntr and expression matrix)
scifate_data.cell_info.head()

                  barcode cell_line time    cell_barcode
0  A549.4h.AAAAACTCTCTCAA      A549   4h  AAAAACTCTCTCAA
1  A549.6h.AAAAAAGAAGTTCA      A549   6h  AAAAAAGAAGTTCA
2  A549.8h.AAAAACGGAGAATA      A549   8h  AAAAACGGAGAATA
3  A549.4h.AAAACGATCCTGGA      A549   4h  AAAACGATCCTGGA
4  A549.6h.AAAAACTGAATTCC      A549   6h  AAAAACTGAATTCC

We can also look and work with the expression_matrix and the NTR matrix in a sparse form and also in a rendered full matrix form.

In [8]:
print(scifate_data.expression_matrix.matrix_sparse)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 43838929 stored elements and shape (7404, 43750)>
  Coords	Values
  (0, 116)	1
  (0, 117)	1
  (0, 124)	1
  (0, 135)	1
  (0, 137)	1
  (0, 143)	3
  (0, 157)	1
  (0, 163)	1
  (0, 173)	1
  (0, 186)	1
  (0, 211)	1
  (0, 217)	2
  (0, 228)	2
  (0, 261)	1
  (0, 276)	2
  (0, 279)	1
  (0, 293)	1
  (0, 294)	2
  (0, 323)	3
  (0, 334)	2
  (0, 343)	2
  (0, 348)	1
  (0, 355)	3
  (0, 357)	4
  (0, 366)	1
  :	:
  (7403, 43699)	3
  (7403, 43701)	4
  (7403, 43702)	17
  (7403, 43704)	2
  (7403, 43706)	1
  (7403, 43707)	19
  (7403, 43709)	1
  (7403, 43712)	10
  (7403, 43713)	2
  (7403, 43715)	26
  (7403, 43717)	19
  (7403, 43721)	88
  (7403, 43728)	68
  (7403, 43730)	72
  (7403, 43731)	91
  (7403, 43733)	6
  (7403, 43735)	3
  (7403, 43737)	69
  (7403, 43738)	22
  (7403, 43739)	88
  (7403, 43740)	201
  (7403, 43744)	57
  (7403, 43745)	380
  (7403, 43747)	1650
  (7403, 43749)	23

In [9]:
print(scifate_data.expression_matrix)

                         MTOR-AS1  ANGPTL7  RPL39P6  SNORA59A  AADACL4  \
A549.4h.AAAAACTCTCTCAA          0        0        0         0        0
A549.6h.AAAAAAGAAGTTCA          0        0        0         0        0
A549.8h.AAAAACGGAGAATA          0        0        0         0        0
A549.4h.AAAACGATCCTGGA          0        0        0         0        0
A549.6h.AAAAACTGAATTCC          0        0        0         0        0
...                           ...      ...      ...       ...      ...
A549.8h.CGCCAACGGAACGC          0        0        0         0        0
A549.6h.CGCCTCTAGTCAAG          0        0        0         0        0
A549.6h.CGCCGCTCATATGC          0        0        0         0        0
A549.2h.CGCCCTTCCAAGAA          0        0        0         0        0
A549.10h.CGCCTTGGAGCTCA         0        0        0         0        0

                         AC244670.1  AADACL3  PRAMEF5  OR4G11P  C1orf158  ...  \
A549.4h.AAAAACTCTCTCAA            0        0        0        0         0  ...
A549.6h.AAAAAAGAAGTTCA            0        0        0        0         0  ...
A549.8h.AAAAACGGAGAATA            0        0        0        0         0  ...
A549.4h.AAAACGATCCTGGA            0        0        0        0         0  ...
A549.6h.AAAAACTGAATTCC            0        0        0        0         0  ...
...                             ...      ...      ...      ...       ...  ...
A549.8h.CGCCAACGGAACGC            0        0        0        0         0  ...
A549.6h.CGCCTCTAGTCAAG            0        0        0        0         0  ...
A549.6h.CGCCGCTCATATGC            0        0        0        0         0  ...
A549.2h.CGCCCTTCCAAGAA            0        0        0        0         0  ...
A549.10h.CGCCTTGGAGCTCA           0        0        0        0         0  ...

                         MT-ND4  MT-TH  MT-TS2  MT-TL2  MT-ND5  MT-RNR1  \
A549.4h.AAAAACTCTCTCAA      542      1       0       0     306     1944
A549.6h.AAAAAAGAAGTTCA      430      0       0       0     160     1016
A549.8h.AAAAACGGAGAATA      321      2       2       0     125      821
A549.4h.AAAACGATCCTGGA      215      0       1       0     119      919
A549.6h.AAAAACTGAATTCC      397      0       0       0     221     1306
...                         ...    ...     ...     ...     ...      ...
A549.8h.CGCCAACGGAACGC     1044      0       2       0     498     2079
A549.6h.CGCCTCTAGTCAAG     1023      0       0       0     336     1678
A549.6h.CGCCGCTCATATGC      280      0       0       0     197     1043
A549.2h.CGCCCTTCCAAGAA      333      0       0       0     121      628
A549.10h.CGCCTTGGAGCTCA     201      0       0       0      57      380

                         MT-TV  MT-RNR2  MT-TL1  MT-ND1
A549.4h.AAAAACTCTCTCAA       0     6380       2     151
A549.6h.AAAAAAGAAGTTCA       0     3715       2      75
A549.8h.AAAAACGGAGAATA       0     3035       1      51
A549.4h.AAAACGATCCTGGA       0     2430       0      33
A549.6h.AAAAACTGAATTCC       0     4498       3      79
...                        ...      ...     ...     ...
A549.8h.CGCCAACGGAACGC       0     7848       1     255
A549.6h.CGCCTCTAGTCAAG       1     5847       1     117
A549.6h.CGCCGCTCATATGC       0     3612       2      49
A549.2h.CGCCCTTCCAAGAA       0     2461       1      51
A549.10h.CGCCTTGGAGCTCA      0     1650       0      23

[7404 rows x 43750 columns]

---
### Working with the data within the dataset 
Because both expression_matrix and ntr_matrix are `LabeledSparseMatrix` objects we can select data by rows and columns to get a new view on the sparse matrix with that we can work.

In [17]:
expression_matrix = scifate_data.expression_matrix

print(f"Type of expression_matrix: {type(expression_matrix)}")

# selecting diverent properties from the expression matrix
expression_4h = expression_matrix.select_rows(time="4h")

print(f"Type of expression_4h: {type(expression_4h)}")

print()
print("Expression Matrix 4h:")
print(expression_4h)

Type of expression_matrix: <class 'sciflow.data.core_dataset.LabeledSparseMatrix'>
Type of expression_4h: <class 'sciflow.data.core_dataset.LabeledSparseMatrix'>

Expression Matrix 4h:
                        MTOR-AS1  ANGPTL7  RPL39P6  SNORA59A  AADACL4  \
A549.4h.AAAAACTCTCTCAA         0        0        0         0        0
A549.4h.AAAACGATCCTGGA         0        0        0         0        0
A549.4h.AAAAATAAGAGGCG         0        0        0         0        0
A549.4h.AAAAGAATCGACGT         0        0        0         0        0
A549.4h.AAAAACTAATTGAG         0        0        0         0        0
...                          ...      ...      ...       ...      ...
A549.4h.CGATGCTCTAACGA         0        0        0         0        0
A549.4h.CGATCCGCTAGCTG         0        0        0         0        0
A549.4h.CGCCATAAGAGGCG         0        0        0         0        0
A549.4h.CGCCAACGTAATCT         0        0        0         0        0
A549.4h.CGCCTAACGGCTGA         0        0        0         0        0

                        AC244670.1  AADACL3  PRAMEF5  OR4G11P  C1orf158  ...  \
A549.4h.AAAAACTCTCTCAA           0        0        0        0         0  ...
A549.4h.AAAACGATCCTGGA           0        0        0        0         0  ...
A549.4h.AAAAATAAGAGGCG           0        0        0        0         0  ...
A549.4h.AAAAGAATCGACGT           0        0        0        0         0  ...
A549.4h.AAAAACTAATTGAG           0        0        0        0         0  ...
...                            ...      ...      ...      ...       ...  ...
A549.4h.CGATGCTCTAACGA           0        0        0        0         0  ...
A549.4h.CGATCCGCTAGCTG           0        0        0        0         0  ...
A549.4h.CGCCATAAGAGGCG           0        0        0        0         0  ...
A549.4h.CGCCAACGTAATCT           0        0        0        0         0  ...
A549.4h.CGCCTAACGGCTGA           0        0        0        0         0  ...

                        MT-ND4  MT-TH  MT-TS2  MT-TL2  MT-ND5  MT-RNR1  MT-TV  \
A549.4h.AAAAACTCTCTCAA     542      1       0       0     306     1944      0
A549.4h.AAAACGATCCTGGA     215      0       1       0     119      919      0
A549.4h.AAAAATAAGAGGCG     101      0       1       0      24      125      0
A549.4h.AAAAGAATCGACGT     216      0       0       0      48      474      1
A549.4h.AAAAACTAATTGAG     377      0       0       0     187     1015      0
...                        ...    ...     ...     ...     ...      ...    ...
A549.4h.CGATGCTCTAACGA     539      0       0       0     228     1125      0
A549.4h.CGATCCGCTAGCTG     476      0       0       0     230     1249      0
A549.4h.CGCCATAAGAGGCG     214      0       1       0      34      190      0
A549.4h.CGCCAACGTAATCT     262      0       0       0      99     1134      0
A549.4h.CGCCTAACGGCTGA     171      0       0       0      52      333      0

                        MT-RNR2  MT-TL1  MT-ND1
A549.4h.AAAAACTCTCTCAA     6380       2     151
A549.4h.AAAACGATCCTGGA     2430       0      33
A549.4h.AAAAATAAGAGGCG      533       0      16
A549.4h.AAAAGAATCGACGT     1742       0      35
A549.4h.AAAAACTAATTGAG     4081       2      61
...                         ...     ...     ...
A549.4h.CGATGCTCTAACGA     4142       1      60
A549.4h.CGATCCGCTAGCTG     5071       0     115
A549.4h.CGCCATAAGAGGCG      712       0      17
A549.4h.CGCCAACGTAATCT     3002       2      58
A549.4h.CGCCTAACGGCTGA     1414       0      32

[1045 rows x 43750 columns]

Because we get a "new" `LabeledSparseMatrix` from the select we can select even further or chain selection operations.

In [ ]:
expression_4h_cells = expression_matrix.select_rows(cell_barcode=["AAAAACTCTCTCAA", "AAAACGATCCTGGA", "AAAAATAAGAGGCG"]).select_cols(gene_id=["ENSG00000225602", "ENSG00000171819", "ENSG00000238173"])

print(expression_4h_cells)

                        MTOR-AS1  ANGPTL7  RPL39P6
A549.4h.AAAAACTCTCTCAA         0        0        0
A549.4h.AAAACGATCCTGGA         0        0        0
A549.4h.AAAAATAAGAGGCG         0        0        0

Now we have three diverent `LabeledSparseMatrix` but we dont save the matrix and the infos in all of them the selected ones will just be a view of the original  `LabeledSparseMatrix`

In [35]:
print(f"Shared matrix object: {id(expression_matrix._matrix) == id(expression_4h._matrix) == id(expression_4h_cells._matrix)}")
print(f"Shared row_info object: {id(expression_matrix._row_info) == id(expression_4h._row_info) == id(expression_4h_cells._row_info)}")
print(f"Shared col_info object: {id(expression_matrix._col_info) == id(expression_4h._col_info) == id(expression_4h_cells._col_info)}")
print()
print(f"Same object: {id(expression_matrix) == id(expression_4h) == id(expression_4h_cells)}")

Shared matrix object: True
Shared row_info object: True
Shared col_info object: True

Same object: False

---
---